In [2]:
import pandas as pd
import numpy as np
from scipy.stats import pearsonr

In [3]:
grants = pd.read_csv('../data/cleansed/cle_grants_employment_startups.csv')

In [5]:
data_fd = pd.read_csv('../data/cleansed/Facilities_Diseases.csv')
data_fd = data_fd.rename(columns={'Unnamed: 0' : 'year'})
data_fd = grants.merge(data_fd, how = 'left', left_on = 'year', right_on = 'year')
data_fd

,year,amount_requested_Culture,amount_requested_Sport,amount_granted_Culture,amount_granted_Sport,amount_given_Culture,amount_given_Sport,nr_one_off_Culture,nr_one_off_Sport,nr_periodic_Culture,...,Fitness in group,Yoga,Cycling,Football,Dancing,Heart- & Artery Disease,Total diseases,Heart- & Artery Disease(%),Total(%),Total facilities sum
0,2016,3314060.67,3007982.24,2082725.84,2744956.71,2078632.28,2675571.41,127.0,48.0,22.0,...,NaN,NaN,NaN,NaN,NaN,1294.0,5517.0,23.5,100.0,832
1,2017,80231568.41,2651958.81,78702906.59,1844397.50,77784362.59,1542359.50,208.0,31.0,66.0,...,9.0,9.0,4.0,5.0,5.0,1206.0,5169.0,23.3,100.0,825
2,2018,81085866.57,2961184.52,78660651.22,2391249.07,77765617.52,1635196.35,214.0,46.0,61.0,...,10.0,9.0,5.0,8.0,6.0,1175.0,5374.0,21.9,100.0,811
3,2019,81679800.65,3629040.94,80455808.80,2194447.34,2868955.36,823125.81,185.0,29.0,27.0,...,11.0,9.0,8.0,8.0,5.0,1155.0,5248.0,22.0,100.0,811
4,2020,92836634.09,552204.69,90353610.81,410738.07,410045.21,3066.30,99.0,1.0,1.0,...,0.0,10.0,14.0,3.0,2.0,NaN,NaN,NaN,NaN,803

In [10]:
data_fd = data_fd[['year', 'amount_given_Sport', 'nr_subsidies_Sport', 'One or more times a week',
       'One or more times a month', 'Fitness (individually)',
       'Sprinting/Jogging', 'Hiking', 'Swimming', 'Fitness in group', 'Yoga',
       'Cycling', 'Football', 'Dancing', 'Heart- & Artery Disease',
       'Total diseases', 'Heart- & Artery Disease(%)', 'Total(%)',
       'Total facilities sum']]

In [11]:
data_fd

,year,amount_given_Sport,nr_subsidies_Sport,One or more times a week,One or more times a month,Fitness (individually),Sprinting/Jogging,Hiking,Swimming,Fitness in group,Yoga,Cycling,Football,Dancing,Heart- & Artery Disease,Total diseases,Heart- & Artery Disease(%),Total(%),Total facilities sum
0,2016,2675571.41,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1294.0,5517.0,23.5,100.0,832
1,2017,1542359.50,45.0,66.0,74.0,26.0,13.0,12.0,11.0,9.0,9.0,4.0,5.0,5.0,1206.0,5169.0,23.3,100.0,825
2,2018,1635196.35,46.0,70.0,76.0,28.0,15.0,12.0,11.0,10.0,9.0,5.0,8.0,6.0,1175.0,5374.0,21.9,100.0,811
3,2019,823125.81,29.0,72.0,78.0,29.0,17.0,13.0,11.0,11.0,9.0,8.0,8.0,5.0,1155.0,5248.0,22.0,100.0,811
4,2020,3066.30,1.0,62.0,68.0,26.0,24.0,21.0,0.0,0.0,10.0,14.0,3.0,2.0,NaN,NaN,NaN,NaN,803

# PERCENTAGE GROWTH

In [12]:
data_per_growth = data_fd.pct_change()
data_per_growth['year'] = data_fd.reset_index()['year']
data_per_growth = data_per_growth.set_index('year')
data_per_growth.transpose()
#No data for 2016 so NaN and since no data for 2016 no growth can be calculated into 2017, so NaN as well.

year                        2016      2017      2018      2019      2020
amount_given_Sport           NaN -0.423540  0.060191 -0.496620 -0.996275
nr_subsidies_Sport           NaN -0.338235  0.022222 -0.369565 -0.965517
One or more times a week     NaN       NaN  0.060606  0.028571 -0.138889
One or more times a month    NaN       NaN  0.027027  0.026316 -0.128205
Fitness (individually)       NaN       NaN  0.076923  0.035714 -0.103448
Sprinting/Jogging            NaN       NaN  0.153846  0.133333  0.411765
Hiking                       NaN       NaN  0.000000  0.083333  0.615385
Swimming                     NaN       NaN  0.000000  0.000000 -1.000000
Fitness in group             NaN       NaN  0.111111  0.100000 -1.000000
Yoga                         NaN       NaN  0.000000  0.000000  0.111111
Cycling                      NaN       NaN  0.250000  0.600000  0.750000
Football                     NaN       NaN  0.600000  0.000000 -0.625000
Dancing                      NaN       NaN  0.200000 -0.166667 -0.600000
Heart- & Artery Disease      NaN -0.068006 -0.025705 -0.017021  0.000000
Total diseases               NaN -0.063078  0.039660 -0.023446  0.000000
Heart- & Artery Disease(%)   NaN -0.008511 -0.060086  0.004566  0.000000
Total(%)                     NaN  0.000000  0.000000  0.000000  0.000000
Total facilities sum         NaN -0.008413 -0.016970  0.000000 -0.009864

# CORRELATION - I

In [13]:
data_fd

,year,amount_given_Sport,nr_subsidies_Sport,One or more times a week,One or more times a month,Fitness (individually),Sprinting/Jogging,Hiking,Swimming,Fitness in group,Yoga,Cycling,Football,Dancing,Heart- & Artery Disease,Total diseases,Heart- & Artery Disease(%),Total(%),Total facilities sum
0,2016,2675571.41,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1294.0,5517.0,23.5,100.0,832
1,2017,1542359.50,45.0,66.0,74.0,26.0,13.0,12.0,11.0,9.0,9.0,4.0,5.0,5.0,1206.0,5169.0,23.3,100.0,825
2,2018,1635196.35,46.0,70.0,76.0,28.0,15.0,12.0,11.0,10.0,9.0,5.0,8.0,6.0,1175.0,5374.0,21.9,100.0,811
3,2019,823125.81,29.0,72.0,78.0,29.0,17.0,13.0,11.0,11.0,9.0,8.0,8.0,5.0,1155.0,5248.0,22.0,100.0,811
4,2020,3066.30,1.0,62.0,68.0,26.0,24.0,21.0,0.0,0.0,10.0,14.0,3.0,2.0,NaN,NaN,NaN,NaN,803

In [14]:
# data_fd = data_fd.transpose()
# data_fd = data_fd.set_index('year')
# data_fd = data_fd.drop(columns=['2016', '2020'])
# np.isinf(data_fd).any()
#data_fd = data_fd.fillna(0)
data_fd = data_fd.reset_index()
# data_fd = data_fd[(data_fd['year'] !=2016) & (data_fd['year'] !=2020)].set_index('year')
data_fd

,index,year,amount_given_Sport,nr_subsidies_Sport,One or more times a week,One or more times a month,Fitness (individually),Sprinting/Jogging,Hiking,Swimming,Fitness in group,Yoga,Cycling,Football,Dancing,Heart- & Artery Disease,Total diseases,Heart- & Artery Disease(%),Total(%),Total facilities sum
0,0,2016,2675571.41,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1294.0,5517.0,23.5,100.0,832
1,1,2017,1542359.50,45.0,66.0,74.0,26.0,13.0,12.0,11.0,9.0,9.0,4.0,5.0,5.0,1206.0,5169.0,23.3,100.0,825
2,2,2018,1635196.35,46.0,70.0,76.0,28.0,15.0,12.0,11.0,10.0,9.0,5.0,8.0,6.0,1175.0,5374.0,21.9,100.0,811
3,3,2019,823125.81,29.0,72.0,78.0,29.0,17.0,13.0,11.0,11.0,9.0,8.0,8.0,5.0,1155.0,5248.0,22.0,100.0,811
4,4,2020,3066.30,1.0,62.0,68.0,26.0,24.0,21.0,0.0,0.0,10.0,14.0,3.0,2.0,NaN,NaN,NaN,NaN,803

In [26]:
data_fd.iloc[:4,[2,3,15,17]]

,amount_given_Sport,nr_subsidies_Sport,Heart- & Artery Disease,Heart- & Artery Disease(%)
0,2675571.41,68.0,1294.0,23.5
1,1542359.50,45.0,1206.0,23.3
2,1635196.35,46.0,1175.0,21.9
3,823125.81,29.0,1155.0,22.0

In [20]:
data_fd.iloc[1:,[2,3,4,5,6,7,8,9,10,11,12,13,14,19]]

,amount_given_Sport,nr_subsidies_Sport,One or more times a week,One or more times a month,Fitness (individually),Sprinting/Jogging,Hiking,Swimming,Fitness in group,Yoga,Cycling,Football,Dancing,Total facilities sum
1,1542359.50,45.0,66.0,74.0,26.0,13.0,12.0,11.0,9.0,9.0,4.0,5.0,5.0,825
2,1635196.35,46.0,70.0,76.0,28.0,15.0,12.0,11.0,10.0,9.0,5.0,8.0,6.0,811
3,823125.81,29.0,72.0,78.0,29.0,17.0,13.0,11.0,11.0,9.0,8.0,8.0,5.0,811
4,3066.30,1.0,62.0,68.0,26.0,24.0,21.0,0.0,0.0,10.0,14.0,3.0,2.0,803

In [29]:
def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'green' if abs(val) <= 0.05 else 'black'
    return 'color: %s' % color

In [30]:
df1 = data_fd.iloc[1:,[2,3,4,5,6,7,8,9,10,11,12,13,14,19]]
df2 = data_fd.iloc[1:,[2,3,4,5,6,7,8,9,10,11,12,13,14,19]]

# np.isnan(df1).any()
# np.isnan(df2).any()

coeffmat = np.zeros((df1.shape[1], df2.shape[1]))
pvalmat = np.zeros((df1.shape[1], df2.shape[1]))

for i in range(df1.shape[1]):    
    for j in range(df2.shape[1]):        
        corrtest = pearsonr(df1[df1.columns[i]], df2[df2.columns[j]])  
        coeffmat[i,j] = corrtest[0]
        pvalmat[i,j] = corrtest[1]
        
dfpvals = pd.DataFrame(pvalmat, columns=df2.columns, index=df1.columns)

dfpvals = dfpvals.style.applymap(color_negative_red)
print('correlation significance')
dfpvals

correlation significance

In [23]:
print('correlation matrix')
df1.corr()

correlation matrix

,amount_given_Sport,nr_subsidies_Sport,One or more times a week,One or more times a month,Fitness (individually),Sprinting/Jogging,Hiking,Swimming,Fitness in group,Yoga,Cycling,Football,Dancing,Total facilities sum
amount_given_Sport,1.000000,0.992639,0.541729,0.666295,0.215561,-0.957385,-0.924226,0.877865,0.803943,-0.877865,-0.982931,0.604288,0.921329,0.748406
nr_subsidies_Sport,0.992639,1.000000,0.617482,0.742196,0.293679,-0.979072,-0.963273,0.928659,0.866385,-0.928659,-0.993921,0.661036,0.948594,0.764487
One or more times a week,0.541729,0.617482,1.000000,0.974245,0.927030,-0.588802,-0.775977,0.826811,0.905021,-0.826811,-0.576262,0.981946,0.824530,0.189001
One or more times a month,0.666295,0.742196,0.974245,1.000000,0.822951,-0.741357,-0.884990,0.925820,0.974632,-0.925820,-0.720082,0.944911,0.890871,0.404865
Fitness (individually),0.215561,0.293679,0.927030,0.822951,1.000000,-0.243709,-0.484322,0.555556,0.679883,-0.555556,-0.234568,0.907218,0.577350,-0.182210
Sprinting/Jogging,-0.957385,-0.979072,-0.588802,-0.741357,-0.243709,1.000000,0.966455,-0.940019,-0.872754,0.940019,0.994177,-0.596962,-0.904534,-0.864018
Hiking,-0.924226,-0.963273,-0.775977,-0.884990,-0.484322,0.966455,1.000000,-0.994135,-0.966045,0.994135,0.960147,-0.780488,-0.971324,-0.727353
Swimming,0.877865,0.928659,0.826811,0.925820,0.555556,-0.940019,-0.994135,1.000000,0.986928,-1.000000,-0.925926,0.816497,0.962250,0.692398
Fitness in group,0.803943,0.866385,0.905021,0.974632,0.679883,-0.872754,-0.966045,0.986928,1.000000,-0.986928,-0.855337,0.886405,0.949671,0.582643
Yoga,-0.877865,-0.928659,-0.826811,-0.925820,-0.555556,0.940019,0.994135,-1.000000,-0.986928,1.000000,0.925926,-0.816497,-0.962250,-0.692398
Cycling,-0.982931,-0.993921,-0.576262,-0.720082,-0.234568,0.994177,0.960147,-0.925926,-0.855337,0.925926,1.000000,-0.604812,-0.919484,-0.830068
Football,0.604288,0.661036,0.981946,0.944911,0.907218,-0.596962,-0.780488,0.816497,0.886405,-0.816497,-0.604812,1.000000,0.864242,0.148774
Dancing,0.921329,0.948594,0.824530,0.890871,0.577350,-0.904534,-0.971324,0.962250,0.949671,-0.962250,-0.919484,0.864242,1.000000,0.568075
Total facilities sum,0.748406,0.764487,0.189001,0.404865,-0.182210,-0.864018,-0.727353,0.692398,0.582643,-0.692398,-0.830068,0.148774,0.568075,1.000000

# CORRELATION - II

In [32]:
df1 = data_fd.iloc[:4,[2,3,15,17]]
df2 = data_fd.iloc[:4,[2,3,15,17]]

# np.isnan(df1).any()
# np.isnan(df2).any()

coeffmat = np.zeros((df1.shape[1], df2.shape[1]))
pvalmat = np.zeros((df1.shape[1], df2.shape[1]))

for i in range(df1.shape[1]):    
    for j in range(df2.shape[1]):        
        corrtest = pearsonr(df1[df1.columns[i]], df2[df2.columns[j]])  
        coeffmat[i,j] = corrtest[0]
        pvalmat[i,j] = corrtest[1]
        
dfpvals = pd.DataFrame(pvalmat, columns=df2.columns, index=df1.columns)
print('correlation significance')
dfpvals = dfpvals.style.applymap(color_negative_red)
dfpvals

correlation significance

In [28]:
print('correlation matrix')
df1.corr()

correlation matrix

,amount_given_Sport,nr_subsidies_Sport,Heart- & Artery Disease,Heart- & Artery Disease(%)
amount_given_Sport,1.000000,0.999614,0.945360,0.699663
nr_subsidies_Sport,0.999614,1.000000,0.948343,0.716503
Heart- & Artery Disease,0.945360,0.948343,1.000000,0.845319
Heart- & Artery Disease(%),0.699663,0.716503,0.845319,1.000000